title: IGC For Science
email: info@igcfs.org
description: >- 
  IGC For Science. Distributed storage for IGC files. 
  Open gliding data and analytics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://igcfs.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  igcfs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
